# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='Post',
        ),
    ]
